## Numpy Array & Basics


In [2]:
import numpy as np 

## Creating Array From List

In [3]:
array_id = np.array([1,2,3,4,5])
print("1D Array : ",array_id)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D Array : ",arr_2d)

1D Array :  [1 2 3 4 5]
2D Array :  [[1 2 3]
 [4 5 6]]


## List vs numpy array

In [4]:
py_list = [1,2,3,4]
print("Python List Multiplication : ",py_list*2)
np_array = np.array([1,2,3,4])
print("Numpy Array Multiplication : ", np_array*2)

Python List Multiplication :  [1, 2, 3, 4, 1, 2, 3, 4]
Numpy Array Multiplication :  [2 4 6 8]


Checking Time

In [5]:
py_list = [1,2,3,4]
print("Python List Multiplication : ",py_list*2)
np_array = np.array([1,2,3,4])
print("Numpy Array Multiplication : ", np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List Operation Time : ",time.time()-start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy Operation Time : ",time.time()-start)

Python List Multiplication :  [1, 2, 3, 4, 1, 2, 3, 4]
Numpy Array Multiplication :  [2 4 6 8]

 List Operation Time :  0.18309473991394043

 Numpy Operation Time :  0.01598834991455078


Creating Array From Scratch

In [11]:
zeros = np.zeros((3,4))
print("Zero Arrays :-\n",zeros)
print("\n")
ones = np.ones((3,4))
print("Ones Arrays :-\n",ones)
print("\n")

full = np.full((3,4), 3)
print("Full Arrays :-\n",full)

print("\n")

random = np.random.random((2,3))
print("Random Array :-\n ",random)

sequence = np.arange(0,11, 2)
print("Sequence : ",sequence)

Zero Arrays :-
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Ones Arrays :-
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Full Arrays :-
 [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


Random Array :-
  [[0.8900605  0.94907969 0.61304905]
 [0.36936121 0.36036594 0.28542218]]
Sequence :  [ 0  2  4  6  8 10]


Vector, Matrix and Tensor

In [17]:
vector = np.array((1,2,3))
print("vector : ",vector)

print("\n")

matrix = np.array([[1,2,3], [4,5,6]])
print("Matrix :-\n",matrix)

print("\n")

tensor = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("Tensor :-\n",tensor)

vector :  [1 2 3]


Matrix :-
 [[1 2 3]
 [4 5 6]]


Tensor :-
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Properties of Array

In [18]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape : ", arr.shape)
print("Dimension : ", arr.ndim)
print("Size : ", arr.size)
print("Data Type : ", arr.dtype)


Shape :  (2, 3)
Dimension :  2
Size :  6
Data Type :  int64


Array Reshaping

In [24]:
arr = np.arange(12)
print("Original Array : ", arr)

reshaped = arr.reshape((3,4))
print("\nReshaped Array :-\n ", reshaped)

flattern = reshaped.flatten()
print("\nFlattern :-\n", flattern)

# ravel (return view, instead of copy)
reveled = reshaped.ravel()
print("\nReveled Array : ", reveled)

#transpose
transpose = reshaped.T
print("\nTranspose of Reshaped :-\n ", transpose)


Original Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped Array :-
  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattern :-
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reveled Array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transpose of Reshaped :-
  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
