Numpy Array Operations

In [2]:
import numpy as np

In [3]:
arr = np.arange(1,11)
print("1-5 : ", arr[0:5])
print("Odd : ", arr[0:5:2])

1-5 :  [1 2 3 4 5]
Odd :  [1 3 5]


In [4]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element : ", arr_2d[1,2])
print("1st Row : ", arr_2d[0])
print("3rd Column : ", arr_2d[:,2])

Specific element :  6
1st Row :  [1 2 3]
3rd Column :  [3 6 9]


Sorting

In [5]:
unsorted = np.array([1,9,0,1,5,6,4,2,7])
print("Unsorted : ", unsorted)
print("Sorted Array : ", np.sort(unsorted))

print("\n")

arr_2d_unsorted = np.array([[3,1],
                            [6,2],
                            [5,3]])
print("Sort Array by Row : \n", np.sort(arr_2d_unsorted, axis = 1))

Unsorted :  [1 9 0 1 5 6 4 2 7]
Sorted Array :  [0 1 1 2 4 5 6 7 9]


Sort Array by Row : 
 [[1 3]
 [2 6]
 [3 5]]


Filtering

In [6]:
numbers = np.arange(1,11)
even = numbers[numbers&1 == False]
print("Even : ", even)

Even :  [ 2  4  6  8 10]


## Filter with mask


In [7]:
mask = numbers > 5
print("Number Greater than 5 : ", numbers[mask])

Number Greater than 5 :  [ 6  7  8  9 10]


## Fancy Indexing VS np.where


In [8]:
indices = [0,2,4]
print(numbers[indices])

# where clause
where_res = np.where(numbers < 5)
print("Number less than 5 : ", numbers[where_res])

[1 3 5]
Number less than 5 :  [1 2 3 4]


## Condition Array


In [9]:
condition_array = np.where(numbers > 5, True, numbers)
print(condition_array)

[1 2 3 4 5 1 1 1 1 1]


## Adding & Removing Data


In [13]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


## Array Compatibility


In [17]:
a = np.array([1,2,3])
b = np.array([3,4,5])
c = np.array([6,7,8,9])

print("Compatibility Shapes (a,b) : ", a.shape == b.shape)
print("Compatibility Shapes (a,c) : ", a.shape == c.shape)
print("Compatibility Shapes (b,c) : ", b.shape == c.shape)


Compatibility Shapes (a,b) :  True
Compatibility Shapes (a,c) :  False
Compatibility Shapes (b,c) :  False


In [20]:
org = np.array([[1,2],
                [3,4]])
new_row = np.array([5,6])

final = np.vstack((org, new_row))
print(org)
print("\n")
print(final)

new_col = np.array([[0],[0],[0]])
final2 = np.hstack((final, new_col))
print("\n")
print(final2)

[[1 2]
 [3 4]]


[[1 2]
 [3 4]
 [5 6]]


[[1 2 0]
 [3 4 0]
 [5 6 0]]


## Delete


In [21]:
arr = np.arange(1,6)
deleted = np.delete(arr, 2)
print(arr)
print(deleted)

[1 2 3 4 5]
[1 2 4 5]
